# ba0fde3d-bee7-4307-b97b-17d0d20aff50
[customizations.installer.kickstart]
contents = """
%post --erroronfail --log=/root/anaconda-post.log
bootc switch --mutate-in-place --transport registry <IMAGE_SIGNED> <UPDATE_IMAGE_REF>

%end
"""
