#!/usr/bin/bash

set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Usage: prime-run <command> [arguments...]" >&2
    exit 2
fi

export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

exec "$@"
